### PR TITLE
2nd Task for verification (fixed & modified)

### PR DESCRIPTION
**Pull request by Uroboric**
I have considered your comments and made changes, the task is ready for verification, the test has passed

### CODE REVIEW

**Comment by vBrooklyn** [comment]
Could you please add requirements.txt file to your repo with all dependancies that you have used. I want to clone your repo and see if I could run a test. Video related to requirements.txt is here https://youtu.be/1jTSK_CKLKY . I have some concerns regarding your POM -> homepage.py class which is missing initializer, so I am wondering if the code going to work. Please add requirements.txt with all dependancies

**Comment by Uroboric** [comment]
I pushed the changes to the branch

**Comment by vBrooklyn** [comment]
Please fix fix Git conflicts that you have. I assume that they are related to your requirements.txt packages versions

**Comment by Uroboric** [comment]
it was terrible, i m stucked & struggled but still found a way out

**Review by vBrooklyn — APPROVED** [review]

**Pull request merged**
